#!/usr/bin/env python

import json
import os
import re
import sys

lines=[]
for line in os.popen("sudo oo-admin-ctl-district -b").readlines():
    lines.append(line.strip())

datas = "".join(lines).replace('=>',': ').split('}{')

for datum in datas[0:len(datas)-1]:
    datas[datas.index(datum)] = datum + '}'
for datum in datas[1:len(datas)]:
    datas[datas.index(datum)] = '{' + datum

results = []
for datum in datas:
    datum = re.sub(r'\"created_at\".*UTC\,\"gear_size\"', '\"gear_size\"', datum)
    datum = re.sub(r'\"updated_at\".*UTC\,\"uuid\"', '\"uuid\"', datum)
    district = json.loads(datum)
    percentage = float(district['available_capacity'])/float(district['max_capacity'])*100
    if percentage < 25:
        results.append((str(district['name']), percentage))

if len(results) > 0:
    returns = "CAPACITY CRITICAL: "
    for result in results:
        returns += ("%s=%.2f " % (result[0], result[1]))
    print returns
    sys.exit(2)
else:
    print "CAPACITY OK"
    sys.exit(0)
